baseURL = "https://squaredcow.dev/"
languageCode = "en-us"
title = "squaredcow"
theme="cactus"
copyright = "© Luis Vaca"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "With time you will discover that anything you spend time unraveling is worth being written"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/warcod3r"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/warcod3r"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/luivaca"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "License"
url = "/license"
weight = 5